#!/bin/bash
PROGRAM_NAME="COOPDocument"
EXTENSION_OUTPUT=pdf
FILENAME="${PROGRAM_NAME}.${EXTENSION_OUTPUT}"
OUTPUT_DIRECTORY=./bin
SOURCE_DIR=./src
ENTRY_FILE_NAME=${SOURCE_DIR}/main.tex
OUTPUT_FORMAT_COMMAND="-output-format=${EXTENSION_OUTPUT}"
OUTPUT_DIR_COMMAND="-output-directory=${OUTPUT_DIRECTORY}" 
INTERATION_MOD_COMMAND="-interaction=nonstopmode"
COMPILER_XX_FLAGS="${OUTPUT_FORMAT_COMMAND} ${OUTPUT_DIR_COMMAND} ${INTERATION_MOD_COMMAND}"
OUTPUT_FILENAME="${OUTPUT_DIRECTORY}/${FILENAME}"
DOCUMENTS_DIR=./documents

function build(){
if [ -e "${OUTPUT_FILENAME}" ] ; then
  echo "Deleting ${OUTPUT_FILENAME}"
  rm -f ${OUTPUT_FILENAME}
fi
 local compile_result=$(pdftex  ${COMPILER_XX_FLAGS} -jobname=${PROGRAM_NAME}  ${ENTRY_FILE_NAME}) 
 if [ -e "${OUTPUT_FILENAME}" ] ; then
   echo "Coping output file=[${OUTPUT_FILENAME}] to ${DOCUMENTS_DIR}/${FILENAME}"
   mv "${OUTPUT_FILENAME}" "${DOCUMENTS_DIR}/${FILENAME}"

 fi

}



build 
